### ISSUE TITLE
What are hybrid webform components?

### ISSUE THREAD

**Issue by luxio** [signalpoint/webform#11]

**Comment by signalpoint** [comment]
@luxio It takes all the "Select options" components and turns each into an individual collapsible set, with a checkbox for each option. It then places an autocomplete at the top of the webform which allows the user to search through all the component options on the form, and upon click will auto scroll and check/uncheck that particular option. It was a financially sponsored feature to build a UX to cope with hundreds and hundreds of select option components on a webform. The name "hybrid" is just the name of the feature itself, and only has to do with DrupalGap Webforms.
