### ISSUE TITLE
Submissions are not shown

### ISSUE THREAD

**Issue by luxio** [signalpoint/webform#12]
When I try to access the results of a webform, I get an error:

`webform_submission_index is deprecated! Use webform_submissions() instead.`

**Comment by luxio** [comment]
Is the current version of webform able to the submitted webform? I could not find the code which would show the data of a user submission?

**Comment by signalpoint** [comment]
@luxio I'd say I remove the `primary_local_tasks` tab from 99.9% of the apps I build these days, so I haven't looked at the Results tab for DrupalGap webform in a while. When I originally wrote it, I believe I only made the Results tab work with the 7.x-3.x version of the Webform Service module. It would need to be updated to work with the 7.x-4.x version instead.
