### ISSUE TITLE
'Description above field' setting of webform component is not considered

### ISSUE THREAD

**Issue by luxio** [signalpoint/webform#16]
There is a webform component setting called  'Description above field'. 
If it is set the description is placed above — rather than below — the field.

**Comment by signalpoint** [comment]
This sounds good, it can go right before the `Submit button` is assembled: https://github.com/signalpoint/webform/blob/7.x-4.x/src/webform.forms.js#L104

I'd recommend just moving the `description` element value to the element's `prefix`, and that should be it. We'd just need to know the machine name of the setting, and where it is buried within the webform object on the node.

**Comment by signalpoint** [comment]
@luxio Whoops, nevermind, I see you've already got a pull request coming in. I'll take a look at that and follow up there.
